name = "AlignedOligs"
uuid = "47e0b4c3-c02b-4df9-862c-39042bcbb8d1"
authors = ["phlaster <phlaster@users.noreply.github.com>"]
version = "0.0.1"

[deps]
FastaIO = "a0c94c4b-ebed-5953-b5fc-82fe598ac79f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
SeqFold = "b3b2a78d-ef5a-44e0-bc1e-af93888afa44"
MAFFT_jll = "72a4bdf2-be5e-5c84-b157-f1dc2927f791"
NCBIBlast = "dcaf3faf-48b5-45a7-abb1-fcfd75344536"

[extensions]
BLASTExt = "NCBIBlast"
MAFFTExt = "MAFFT_jll"
SeqFoldExt = "SeqFold"

[compat]
FastaIO = "1.1.0"
MAFFT_jll = "7.525.0"
NCBIBlast = "0.2.0"
ProgressMeter = "1.11.0"
SeqFold = "0.4.0"
Random = "1.10"
Statistics = "1.10"
julia = "1.10"
